[global]
error_log = /proc/self/fd/2
daemonize = no
[oms]
listen = 127.0.0.1:9070
pm = ondemand
pm.max_children = 2
pm.process_idle_timeout = 20s
pm.max_requests = 500
catch_workers_output = yes
clear_env = no
php_admin_value[memory_limit] = 96M
php_admin_flag[display_errors] = off
php_admin_flag[log_errors] = on
php_admin_value[error_log] = /app/storage/logs/php.log
php_admin_value[opcache.memory_consumption] = 32
php_admin_value[opcache.interned_strings_buffer] = 4
php_admin_value[opcache.max_accelerated_files] = 6000
php_admin_flag[opcache.validate_timestamps] = 0
php_admin_flag[opcache.enable_file_override] = 1
