"""Bind a real successful build to unchanged source inputs and generated bytes."""
import hashlib
import json
from pathlib import Path
import subprocess

root = Path(__file__).resolve().parent.parent
paths = ('resources/js', 'resources/css', 'resources/fonts', 'package.json', 'package-lock.json', 'webpack.config.js', 'tsconfig.json', '.node-version')
names = subprocess.check_output(['git', '-C', str(root), 'ls-files', '-z', '--', *paths]).decode().split('\0')
def inputs():
    return {name: hashlib.sha256((root / name).read_bytes()).hexdigest() for name in names if name}
before = inputs()
with (root / 'artifacts/production/compiled-build.log').open('x') as output:
    subprocess.run(['npm', 'run', 'prod'], cwd=root, stdout=output, stderr=subprocess.STDOUT, check=True)
assert before == inputs(), 'Build inputs changed while compiling'
assets = {path.relative_to(root).as_posix(): hashlib.sha256(path.read_bytes()).hexdigest() for path in sorted((root / 'public/assets').rglob('*')) if path.is_file()}
target = root / 'artifacts/production/compiled-inputs.json'
with target.open('x') as output:
    json.dump({'inputs': before, 'assets': assets, 'passed': True}, output, indent=2)
print(json.dumps({'compiled_files': len(assets), 'source_files': len(before), 'passed': True}))
